export const data = {
  products: [
    {
      id: 1,
      title: "Product 1",
      description: "Product 1 description",
      price: 100,
      image: "/11.jpg",
    },
    {
      id: 2,
      title: "Product 2",
      description: "Product 2 description",
      price: 200,
      image: "/12.jpg",
    },
    {
      id: 3,
      title: "Product 3",
      description: "Product 3 description",
      price: 300,
      image: "/13.jpg",
    },
    {
      id: 4,
      title: "Product 4",
      description: "Product 4 description",
      price: 400,
      image: "/14.jpg",
    },
    {
      id: 5,
      title: "Product 5",
      description: "Product 5 description",
      price: 500,
      image: "/15.jpg",
    },
    {
      id: 6,
      title: "Product 6",
      description: "Product 6 description",
      price: 600,
      image: "/16.jpg",
    },
    {
      id: 7,
      title: "Product 7",
      description: "Product 7 description",
      price: 700,
      image: "/17.jpg",
    },
    {
      id: 8,
      title: "Product 8",
      description: "Product 8 description",
      price: 800,
      image: "/18.jpg",
    },
    {
      id: 9,
      title: "Product 9",
      description: "Product 9 description",
      price: 900,
      image: "/19.jpg",
    },
    {
      id: 10,
      title: "Product 10",
      description: "Product 10 description",
      price: 1000,
      image: "/20.jpg",
    },
  ],
};
